src/Entity/Atelier.php
<?php

namespace App\Entity;

use App\Repository\AtelierRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: AtelierRepository::class)]
#[Vich\Uploadable]
class Atelier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $titre = null;
 
    #[ORM\ManyToOne(inversedBy: 'ateliers')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Location $Location = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $begin_datetime = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_datetime = null;

    #[ORM\Column(length: 6000, nullable: true)]
    private ?string $content = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'ns_img', fileNameProperty: 'imageName' )]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $img = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->Location;
    }

    public function setLieu(?string $Location): static
    {
        $this->Location = $Location;

        return $this;
    }

    public function getBeginDatetime(): ?\DateTimeInterface
    {
        return $this->begin_datetime;
    }

    public function setBeginDatetime(?\DateTimeInterface $begin_datetime): static
    {
        $this->begin_datetime = $begin_datetime;

        return $this;
    }

    public function getEndDatetime(): ?\DateTimeInterface
    {
        return $this->end_datetime;
    }

    public function setEndDatetime(?\DateTimeInterface $end_datetime): static
    {
        $this->end_datetime = $end_datetime;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getImg()
    {
        return $this->img;
    }

    public function setImg($img): static
    {
        $this->img = $img;

        return $this;
    }

     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $img): void
    {
        $this->img = $img;
    }

    public function getImageName(): ?string
    {
        return $this->img;
    }

    public function getLocation(): ?Location
    {
        return $this->Location;
    }

    public function setLocation(?Location $Location): static
    {
        $this->Location = $Location;

        return $this;
    }
}

src/Controller/ConcertListController.php
<?php

namespace App\Controller;

use App\Repository\ConcertRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class ConcertListController extends AbstractController
{
    #[Route('/concert/list', name: 'app_concert_list')]
    public function index(ConcertRepository $repository): Response
    {
        //Création de l'encodeur JSON
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $concerts= $repository->findAll();

       
        return $this->json($concerts); /*$serializer->serialize(, 'json'));*/
        
    }
    /*public function list(ConcertRepository $repository): Response
    {
        $concerts= $repository->findAll();

        return $this->render('concert_list/index.html.twig', [
            'concerts' =>$concerts]);

    }*/
}

templates/concert_list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Concerts{% endblock %}

{% block body %}


<main>
    <h1>Listes des concerts</h1>

    {% for message in app.flashes('success')%}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor %}

    <table class="table table-hover">
        {% for concert in concerts %}
            <thead>
                <th>Concert {{concert.id}}</th>
            </thead>
            <tbody class="d-flex flex-row">  
                <tr class="table-primary d-flex flex-column">
                    <td>
                        <h2>{{concert.titre}}</h2>
                    </td>
                    <td>
                        <h3>Lieu:</h3>
                        {#<p>{{concert.location}}</p>#}
                    </td>
                    <td>
                        <h3>Date de début:</h3>
                        <p>{{concert.beginDatetime|format_datetime()}}</p>
                    </td>
                    <td>
                        <h3>Date de fin:</h3>
                        <p>{{concert.endDatetime|format_datetime()}}</p>
                    </td>
                    <td>
                        <h3>Description:</h3>
                        <p>{{concert.content}}</p>
                    </td>
                
                    
                </tr>

                <tr class="table-primary d-flex flex-column">
                    <td><img src="{{vich_uploader_asset(concert, 'imageFile')}}" width="200px"></td>
                     <td><a class="button-style" href="{{path("app_concert_edit", {'id' : concert.id })}}">Modifier la fiche</a></td>
                    <td><a class="button-style" href="{{path("app_concert_delete", {'id' : concert.id })}}">Supprimer la fiche</a></td>
                </tr>
            </tbody>
            
        {% endfor %}    
    </table>
    <div class="d-flex flex-row">
        <div class="navigation">
            {{ knp_pagination_render(concerts) }}
        </div>
        <div class="count">
            <p> Nombre de fiches: {{concerts.getTotalItemCount}}</p>
        </div>

    </div>
    
</main>


{% endblock %}